version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
        # For Lodash, ignore all updates
      - dependency-name: "lodash"
      - dependency-name: "nodemailer"